region = "region "
access_key = "access_key"
secret_key = ""secret_key
vpc_cidr = "192.168.0.0/16"
vpc_name = "myvpc"
igw_name = "myigw"
subnet_cidr = ["192.168.0.0/24" ,"192.168.1.0/24"]
subnet_name = ["public_subnet1" , "public_subnet2"]
availability_zones = ["us-east-1a","us-east-1b"]
pub_rt_name = "public_rt"
imagename = "imagename"
instance_type = "t2.micro"
instance_name = "myinstance"
